# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-05 01:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20170605_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 9, 47, 32, 524000)),
        ),
    ]
