# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-05 04:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20170605_1219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='summarie',
            new_name='summar',
        ),
        migrations.AlterField(
            model_name='summary',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 5, 12, 24, 19, 425000)),
        ),
    ]
