# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-08 07:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20170608_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='username',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 15, 23, 17, 263000)),
        ),
    ]
