# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-10 07:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20170608_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='activity_id',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='actor_url',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='actor_username',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='automated_response',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='created_at',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='editable',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='is_internal',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='report_id',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='team_handle',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='type',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='updated_at',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='allow_singular_disclosure_after',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='allow_singular_disclosure_at',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='can_view_team',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='comments_closed',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='created_at',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='cve_ids',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='disclosed_at',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='has_bounty',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='is_external_bug',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='is_participant',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='public',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='report_id',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='severity_rating',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='singular_disclosure_allowed',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='singular_disclosure_disabled',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='state',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='substate',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='team_about',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='team_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='team_url',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='url',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='username_url',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='visibility',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='vote_count',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='vulnerability_information',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='vulnerability_information_html',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='summar',
            name='can_create',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='summar',
            name='can_view',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='summar',
            name='category',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='summar',
            name='content',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='summar',
            name='content_html',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='summar',
            name='report_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='summar',
            name='summaries_id',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 10, 15, 37, 25, 998205)),
        ),
        migrations.AlterField(
            model_name='summary',
            name='pages',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='total_reports',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
